// <auto-generated />

using System;
using System.Diagnostics;
using System.Resources;
using System.Runtime.CompilerServices;

#nullable enable

namespace Borm.Properties; 
public static class Strings 
{
    private static readonly ResourceManager ResourceManager = new("Borm.Properties.Strings", typeof(Strings).Assembly);

    /// <summary>
    /// Data context is not initialized.
    /// </summary>
    public static string DataContextNotInitialized() => GetString();

    /// <summary>
    /// Duplicate column index '{index}' found in entity '{entityTypeName}'.
    /// </summary>
    public static string DuplicateColumnIndex(int index, string entityTypeName) => GetString([index, entityTypeName]);

    /// <summary>
    /// Duplicate column name '{name}' found in entity '{entityTypeName}'.
    /// </summary>
    public static string DuplicateColumnName(string name, string entityTypeName) => GetString([name, entityTypeName]);

    /// <summary>
    /// Entity '{entityName}' must have at least 1 column.
    /// </summary>
    public static string EmptyColumnCollection(string entityName) => GetString([entityName]);

    /// <summary>
    /// Circular Reference. Entity '{entityTypeName}' cannot depend on itself.
    /// </summary>
    public static string EntityDependencyCircularReference(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// Referenced entity type {entityTypeName} does not exist.
    /// </summary>
    public static string EntityDependencyNotFound(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// The entity type '{entityTypeName}' cannot be abstract.
    /// </summary>
    public static string EntityTypeCannotBeAbstract(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// Entity type '{typeName}' was not decorated with '{attributeName}'.
    /// </summary>
    public static string EntityTypeNotDecorated(string typeName, string attributeName) => GetString([typeName, attributeName]);

    /// <summary>
    /// Column index cannot be lesser than zero.
    /// </summary>
    public static string InvalidColumnIndex() => GetString();

    /// <summary>
    /// The type '{entityTypeName}' does not have a public constructor that would initialise all columns.
    /// </summary>
    public static string InvalidEntityTypeConstructor(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// The foreign key property must be of the referenced type or the type of its primary key. Entity: '{entityTypeName}'.
    /// </summary>
    public static string InvalidForeignKeyDataType(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// Only member expressions: `e => e.Property` are allowed.
    /// </summary>
    public static string InvalidMemberExpression() => GetString();

    /// <summary>
    /// Command executor is missing. Call '{firstMethod}' or '{secondMethod}'.
    /// </summary>
    public static string MissingCommandExecutor(string firstMethod, string secondMethod) => GetString([firstMethod, secondMethod]);

    /// <summary>
    /// Command definition factory is missing. Call '{methodNamed}'.
    /// </summary>
    public static string MissingDefinitionFactory(string methodName) => GetString([methodName]);

    /// <summary>
    /// Entity model is missing. Call '{methodName}'.
    /// </summary>
    public static string MissingEntityModelConfiguration(string methodName) => GetString([methodName]);

    /// <summary>
    /// Entity '{entityName}' has no primary key.
    /// </summary>
    public static string MissingPrimaryKey(string entityName) => GetString([entityName]);

    /// <summary>
    /// The data context does not contain a table for the entity of type '{entityTypeName}'.
    /// </summary>
    public static string MissingTableForEntity(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// The transaction attempted to modify a row that had been removed by another transaction.
    /// </summary>
    public static string ModificationOfNonExistingRow() => GetString();

    /// <summary>
    /// Multiple primary keys are not allowed for entities. Type: `{entityName}`.
    /// </summary>
    public static string MultiplePrimaryKeys(string entityName) => GetString([entityName]);

    /// <summary>
    /// No public property '{propName}' is declared in a type '{entityTypeName}'.
    /// </summary>
    public static string NoPublicPropertyDeclared(string propName, string entityTypeName) => GetString([propName, entityTypeName]);

    /// <summary>
    /// The column '{columnName}' in the table '{tableName}' cannot be set to null.
    /// </summary>
    public static string NullableConstraintViolation(string columnName, string tableName) => GetString([columnName, tableName]);

    /// <summary>
    /// Primary key cannot be nullable. Entity: '{entityTypeName}'.
    /// </summary>
    public static string NullablePrimaryKey(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// Primary key cannot be a foreign key. Entity: '{entityTypeName}'.
    /// </summary>
    public static string PrimaryKeyAsForeignKey(string entityTypeName) => GetString([entityTypeName]);

    /// <summary>
    /// The table '{tableName}' already contains a row with the primary key '{primaryKey}'.
    /// </summary>
    public static string PrimaryKeyConstraintViolation(string tableName, object primaryKey) => GetString([tableName, primaryKey]);

    /// <summary>
    /// Table '{tableName}' does not contain row with the primary key '{primaryKey}'.
    /// </summary>
    public static string RowNotFound(string tableName, object primaryKey) => GetString([tableName, primaryKey]);

    /// <summary>
    /// The transaction failed because one of the operations within it threw an exception.
    /// </summary>
    public static string TransactionFailed() => GetString();

    /// <summary>
    /// The maximum number of reruns for a transaction has been exceeded.
    /// </summary>
    public static string TransactionMaxRerunsExceeded() => GetString();

    /// <summary>
    /// Type '{typeName}' is not supported.
    /// </summary>
    public static string TypeNotSupported(string typeName) => GetString([typeName]);

    /// <summary>
    /// The table '{tableName}' already contains a row where the value of the column '{columnName}' is '{columnValue}'.
    /// </summary>
    public static string UniqueConstraintViolation(string tableName, string columnName, object? columnValue) => GetString([tableName, columnName, columnValue]);

    /// <summary>
    /// Validation failed for column "{columnName}" of entity "{entityName}".
    /// </summary>
    public static string ValidationFailedWithMetadata(string columnName, string entityName) =>
        GetString([columnName, entityName]);

    /// <summary>
    /// Validator type "{validatorTypeName}" must implement "{validatorIFaceName}".
    /// </summary>
    public static string ValidatorDoesNotImplementInterface(string validatorTypeName, string validatorIFaceName) =>
        GetString([validatorTypeName, validatorIFaceName]);

    /// <summary>
    /// Validator "{validatorTypeName}" must have a parameterless public constructor.
    /// </summary>
    public static string ValidatorNoPublicDefaultCtor(string validatorTypeName) => GetString([validatorTypeName]);

    private static string GetString(object?[]? formatArgs, [CallerMemberName] string? resourceName = null)
    {
        string msgFormat = GetString(resourceName);
        return formatArgs == null ? msgFormat : string.Format(msgFormat, formatArgs);
    }

    private static string GetString([CallerMemberName] string? resourceName = null)
    {
        string? message = ResourceManager.GetString(resourceName!);
        Debug.Assert(!string.IsNullOrEmpty(message), $"The resource with the name '{resourceName}' could not be found.");
        return message;
    }
}
