name: Build Test
on:
    pull_request:
        branches:
            - main

jobs:
    tests:
        name: Unit and E2E tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x
            - name: Restore
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: Run Unit Tests
              run: dotnet test Borm.Tests.slnf --no-build --verbosity normal
            - name: Run E2E Tests
              run: dotnet test ./tests/Borm.Tests.EndToEnd/Borm.Tests.EndToEnd.csproj --no-build --verbosity normal
