name: merge-main
on:
    pull_request:
        branches:
            - main

jobs:
    tests:
        name: Unit and E2E tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - name: Restore
              run: dotnet restore
            
            - name: Run Unit Tests
              run: dotnet test ./tests/Borm.Tests/Borm.Tests.csproj --no-build --verbosity normal

            - name: Run E2E Tests
              run: dotnet test ./tests/Borm.Tests.EndToEnd/Borm.Tests.EndToEnd.csproj --no-build --verbosity normal
    
    code-analysis:
        name: Code Analysis
        runs-on: ubuntu-latest
        needs: tests
        permissions:
            security-events: write
            actions: read
            contents: read

        strategy:
            fail-fast: false
            matrix:
                language: [ 'csharp' ]
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                languages: ${{ matrix.language }}

            - name: Autobuild
              uses: github/codeql-action/autobuild@v3

            - name: Analyse
              uses: github/codeql-action/analyze@v3